{{- range .Values.ec2NodeClasses }}
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ .name }}
spec:
  role: {{ .role }}
  amiFamily: {{ .amiFamily }}
  securityGroupSelectorTerms:
    - id: {{ .securityGroupId }}
  subnetSelectorTerms:
    {{- range .subnetIds }}
    - id: {{ . }}
    {{- end }}
  blockDeviceMappings:
    {{- range .blockDeviceMappings }}
    - deviceName: {{ .deviceName }}
      ebs:
        volumeSize: "{{ .ebs.volumeSize }}"
        volumeType: "{{ .ebs.volumeType }}"
        deleteOnTermination: {{ .ebs.deleteOnTermination }}
        encrypted: {{ .ebs.encrypted }}
    {{- end }}
  tags:
    {{- range $key, $value := .tags }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
---
{{- end }}
