# templates/ec2nodeclasses.yaml
{{- if .Values.customResources.enabled }}
{{- range .Values.customResources.ec2NodeClasses }}
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ .name }}
spec:
  amiFamily: {{ .properties.amiFamily }}
  securityGroupSelectorTerms:
    - matchExpressions:
        - key: "aws:ec2:security-group"
          operator: "In"
          values: 
            {{- range .properties.securityGroups }}
            - {{ . | quote }}
            {{- end }}
  subnetSelectorTerms:
    - matchExpressions:
        - key: "aws:ec2:subnet-id"
          operator: "In"
          values: 
            {{- range .properties.subnets }}
            - {{ . | quote }}
            {{- end }}
{{- end }}
{{- end }}
