apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dynamoai.fullname" . }}-{{ .Values.redis.name }}-config
  labels:
    {{- include "dynamoai.labels" . | nindent 4 }}
  annotations:
    {{- include "dynamoai.annotations" . | nindent 4 }}
data:
  host: "{{ include "dynamoai.fullname" . }}-{{ .Values.redis.name }}.{{ .Release.Namespace }}.svc.cluster.local"
  port: "{{ .Values.redis.service.port }}"
  address: "{{ include "dynamoai.fullname" . }}-{{ .Values.redis.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.redis.service.port }}"
