apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynamoai.fullname" . }}-{{ .Values.redis.name }}-secret
  labels:
    {{- include "dynamoai.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ printf "%s-%s.%s.svc.cluster.local" (include "dynamoai.fullname" .) .Values.redis.name .Release.Namespace | b64enc | quote }}
  port: {{ .Values.redis.service.port | toString | b64enc | quote }}
  address: {{ printf "%s-%s.%s.svc.cluster.local:%s" (include "dynamoai.fullname" .) .Values.redis.name .Release.Namespace (.Values.redis.service.port | quote) | b64enc | quote }}
