{{- if .Values.keycloak.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: dynamoai-keycloak-auth-secret
type: Opaque
data:
  admin-password: {{ .Values.secrets.authAdminPassword | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: dynamoai-keycloak-psql-db-secret
type: Opaque
data:
  postgres-password: {{ .Values.secrets.keycloakPsqlPassword | b64enc | quote }}

{{- end }}
