apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dynamoai.fullname" . }}-rolebinding
  labels:
    {{- include "dynamoai.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dynamoai.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "dynamoai.serviceAccountName" . }}
