{{- if .Values.secrets.common.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynamoai.fullname" . }}-common-secret
type: Opaque
data:
  defaultUserPassword: {{ .Values.secrets.common.defaultUserPassword | b64enc | quote }}
  defaultUserEmail: {{ .Values.secrets.common.defaultUserEmail | b64enc | quote }}
  defaultUserApiKey: {{ .Values.secrets.common.defaultUserApiKey | b64enc | quote }}
  platformAdminPassword: {{ .Values.secrets.common.platformAdminPassword | b64enc | quote }}
  license: {{ .Values.secrets.common.license | b64enc | quote }}
  serviceUserApiKeyMap: {{ .Values.secrets.common.serviceUserApiKeyMap | b64enc | quote }}
  openaiApiKey: {{ .Values.secrets.common.openaiApiKey | b64enc | quote }}
  mistralApiKey: {{ .Values.secrets.common.mistralApiKey | b64enc | quote }}
  pentestServiceUserApiKey: {{ .Values.secrets.common.pentestServiceUserApiKey | b64enc | quote }}
  dataGenerationApiKey: {{ .Values.secrets.common.dataGenerationApiKey | b64enc | quote }}
  hfToken: {{ .Values.secrets.common.hfToken | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynamoai.fullname" . }}-mongodb-secret
type: Opaque
data:
  host: {{ .Values.secrets.mongodb.host | b64enc | quote }}
  port: {{ .Values.secrets.mongodb.port | b64enc | quote }}
  username: {{ .Values.secrets.mongodb.username | b64enc | quote }}
  password: {{ .Values.secrets.mongodb.password | b64enc | quote }}
  name: {{ .Values.secrets.mongodb.name | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynamoai.fullname" . }}-postgresql-secret
type: Opaque
data:
  host: {{ .Values.secrets.postgresql.host | b64enc | quote }}
  port: {{ .Values.secrets.postgresql.port | b64enc | quote }}
  username: {{ .Values.secrets.postgresql.secrets.username | b64enc }}
  password: {{ .Values.secrets.postgresql.secrets.password | b64enc }}
  name: {{ .Values.secrets.postgresql.name | b64enc | quote }}
{{- end }}

