{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynamoai.fullname" . }}-common-secret
type: Opaque
data:
  default_user_password: {{ .Values.secrets.common.defaultUserPassword | b64enc | quote }}
  default_user_email: {{ .Values.secrets.common.defaultUserEmail | b64enc | quote }}
  default_user_api_key: {{ .Values.secrets.common.defaultUserApiKey | b64enc | quote }}
  platform_admin_password: {{ .Values.secrets.common.platformAdminPassword | b64enc | quote }}
  license: {{ .Values.secrets.common.license | b64enc | quote }}
  service_user_api_key_map: {{ .Values.secrets.common.serviceUserApiKeyMap | b64enc | quote }}
  openai_api_key: {{ .Values.secrets.common.openaiApiKey | b64enc | quote }}
  mistral_api_key: {{ .Values.secrets.common.mistralApiKey | b64enc | quote }}
  pentest_service_user_api_key: {{ .Values.secrets.common.pentestServiceUserApiKey | b64enc | quote }}
  data_generation_api_key: {{ .Values.secrets.common.dataGenerationApiKey | b64enc | quote }}
  hf_token: {{ .Values.secrets.common.hfToken | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynamoai.fullname" . }}-mongodb-secret
type: Opaque
data:
  host: {{ .Values.secrets.mongodb.host | b64enc | quote }}
  port: {{ .Values.secrets.mongodb.port | b64enc | quote }}
  username: {{ .Values.secrets.mongodb.username | b64enc | quote }}
  password: {{ .Values.secrets.mongodb.password | b64enc | quote }}
  name: {{ .Values.secrets.mongodb.name | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynamoai.fullname" . }}-postgres-secret
type: Opaque
data:
  host: {{ .Values.secrets.postgres.host | b64enc | quote }}
  port: {{ .Values.secrets.postgres.port | b64enc | quote }}
  username: {{ .Values.secrets.postgres.username | b64enc }}
  password: {{ .Values.secrets.postgres.password | b64enc }}
  name: {{ .Values.secrets.postgres.name | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynamoai.fullname" . }}-mongodb-secret
type: Opaque
data:
  host: {{ .Values.secrets.mongodb.host | b64enc | quote }}
  port: {{ .Values.secrets.mongodb.port | b64enc | quote }}
  username: {{ .Values.secrets.mongodb.username | b64enc | quote }}
  password: {{ .Values.secrets.mongodb.password | b64enc | quote }}
  name: {{ .Values.secrets.mongodb.name | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dynamoai.fullname" . }}-apikeys-secret
type: Opaque
data:
  dynamoai.guard.apikeys: 
    {{- $mistralKeys := join "," .Values.secrets.apikeys.mistral }}
    {{- $mistralEncoded := b64enc $mistralKeys }}
    {{ $mistralEncoded | quote }}
  dynamoai.pentest.apikeys.mistral: 
    {{- $mistralKeys := join "," .Values.secrets.apikeys.mistral }}
    {{- $mistralEncoded := b64enc $mistralKeys }}
    {{ $mistralEncoded | quote }}
  dynamoai.pentest.apikeys.openai: 
    {{- $openaiKeys := join "," .Values.secrets.apikeys.openai }}
    {{- $openaiEncoded := b64enc $openaiKeys }}
    {{ $openaiEncoded | quote }}
{{- end }}