{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dynamoai.serviceAccountName" . }}
  labels:
    {{- include "dynamoai.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "dynamoai.annotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
imagePullSecrets:
  {{- if .Values.global.imagePullSecrets }}
  {{- toYaml .Values.global.imagePullSecrets | nindent 2 }}
  {{- end }}
{{- end }}