{{- if $.Values.nats.enabled }}
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: data-processing-nats-consumer
spec:
    streamName: {{ $.Values.nats.stream.name }}
    durableName:  data-processing-nats-consumer
    filterSubject: {{ $.Values.dataProcessing.nats.subjectFilter }}
    ackPolicy: 'explicit'
    ackWait: '200m'
    maxAckPending: 10
    maxDeliver: 3
{{- end }}
