{{- if $.Values.dataProcessing.nats.enabled }}
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: data-processing-nats-consumer
spec:
    streamName: {{ $.Values.dataProcessing.nats.stream.name }}
    durableName: {{ $.Values.dataProcessing.nats.stream.name }}
    filterSubject: {{ .Values.dataProcessing.nats.stream.subjects }}
    ackPolicy: 'explicit'
    ackWait: '60s'
    maxAckPending: 100
    maxDeliver: 3
{{- end }}
