# Default values for dynamoai-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imagePullSecrets: []
  nameOverride: "dynamoai"
  fullnameOverride: "dynamoai"
  serviceAccount:
    name: "dynamoai-service-account"
  awsRegion: "us-east-1"

proxy:
  http: ""
  https: ""
  noProxy: "" 

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}


config: 
  testReportGenerationEnabled: false
  remoteModelConfigValidationApiEnabled: false
  huggingfaceApiRequestsEnabled: false
  rateLimitDynamoGuard: true
  rateLimitDynamoEval: true
  pbacSafetyModeEnabled: true
  bucketName: "dynamoai-pentest-bucket"
  corsRule: "allow-all"
  awsRegion: "us-east-1"
  cognitoUserPoolId: "123"
  cognitoClientId: "223"

