# Default values for dynamoai-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imagePullSecrets: []
  nameOverride: "dynamoai"
  fullnameOverride: "dynamoai"
  serviceAccount:
    name: "dynamoai-service-account"
  awsRegion: "us-east-1"

proxy:
  http: ""
  https: ""
  noProxy: "" 

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
    # eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/my-role
  


config: 
  testReportGenerationEnabled: true
  remoteModelConfigValidationApiEnabled: false
  huggingfaceApiRequestsEnabled: false
  rateLimitDynamoGuard: true
  rateLimitDynamoEval: true
  pbacSafetyModeEnabled: true
  bucketName: "dynamoai-pentest-bucket"
  corsRule: "allow-all"
  cognitoUserPoolId: "123"
  cognitoClientId: "223"

secrets:
  create: true
  common:
    defaultUserPassword: ""
    defaultUserEmail: ""
    defaultUserApiKey: ""
    platformAdminPassword: ""
    license: ""
    serviceUserApiKeyMap: ""
    pentestServiceUserApiKey: ""
    dataGenerationApiKey: ""
    hfToken: ""
  apikeys:
    openai:
      - "abc"
    mistral: 
      - "def"
    azure_openai: ""
    azure_mistral: ""

  postgres:
    host: ""
    port: ""
    username: ""
    password: ""
    name: ""
    keycloakDbName: ""

  mongodb:
    host: ""
    port: ""
    username: ""
    password: ""
    name: ""