{{- if .Values.inputJapanese.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dynamoai.fullname" . }}-{{ .Values.inputJapanese.name }}
  labels:
    {{- include "dynamoai.labels" . | nindent 4 }}
    {{- with .Values.inputJapanese.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "dynamoai.annotations" . | nindent 4 }}
    {{- with .Values.inputJapanese.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.inputJapanese.service.type }}
  ports:
    - port: {{ .Values.inputJapanese.service.port }}
      targetPort: {{ .Values.inputJapanese.port }}
      protocol: TCP
  selector:
    app: {{ include "dynamoai.fullname" . }}-{{ .Values.inputJapanese.name }}
    {{- include "dynamoai.labels" . | nindent 4 }}
{{- end }}