apiVersion: v2
name: dynamoai-base
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.6

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: "mongodb"
    version: "12.1.16"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: "minio"
    version: "14.6.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: minio.enabled
  - name: keycloak
    version: "21.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: keycloak.enabled
  - name: "dynamoai-core"
    version: "0.1.2"
    repository: "https://documentation.dynamofl.com/helm"
    condition: dynamoai-core.enabled
  - name: "dynamoai-api"
    version: "0.1.3"
    repository: "https://documentation.dynamofl.com/helm"
    condition: dynamoai-api.enabled
  - name: "dynamoai-ui"
    version: "0.1.3"
    repository: "https://documentation.dynamofl.com/helm"
    condition: dynamoai-ui.enabled
  - name: "dynamoai-redis"
    version: "0.1.1"
    repository: "https://documentation.dynamofl.com/helm"
    condition: dynamoai-redis.enabled
  - name: "dynamoai-metrics-server"
    version: "0.1.1"
    repository: "https://documentation.dynamofl.com/helm"
    condition: dynamoai-metrics-server.enabled
