{{- if .Values.finetuning.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ .Values.finetuning.name }}
spec:
  jobTargetRef:
    parallelism: 1
    completions: 1
    template:
      spec:
        {{- with .Values.finetuning.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        containers:
          - name: redis-client
            image: {{ .Values.finetuning.image.registry }}/{{ .Values.finetuning.image.repository }}:{{ .Values.finetuning.image.tag }}
            imagePullPolicy: {{ .Values.finetuning.image.pullPolicy }}
            resources:
              {{- toYaml .Values.finetuning.resources | nindent 14 }}
            env:
              {{- if .Values.nats.enabled }}
              - name: NATS_SERVER
                value: {{ $.Values.nats.serverUrl }}
              - name: NATS_ENABLED
                value: "true"
              - name: NATS_SUBJECT_FILTER
                value: {{ .Values.finetuning.nats.subjectFilter}}
              - name: NATS_CONSUMER_NAME
                value: finetuning-nats-consumer
              {{- end }}
              {{- include "dynamoai.commonEnv" . | nindent 14 }}
              {{- include "dynamoai.finetuningScaledJobEnv" . | nindent 14 }}
              {{- with .Values.finetuning.extraEnv }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- if $.Values.global.config.proxy }}
            envFrom:
              - configMapRef:
                  name: {{ $.Values.global.config.proxy }}
            {{- end }}
        restartPolicy: {{ .Values.finetuning.restartPolicy }}
  pollingInterval: {{ .Values.finetuning.pollingInterval }}
  minReplicaCount: {{ .Values.finetuning.minReplicaCount }}
  maxReplicaCount: {{ .Values.finetuning.maxReplicaCount }}
  successfulJobsHistoryLimit: {{ .Values.finetuning.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.finetuning.failedJobsHistoryLimit }}
  triggers:
    - type: external
      metadata:
        scalerAddress: {{ .Values.metricsServer.address }}
        listName: {{ .Values.finetuning.name }}
        listLength: '1'
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "dynamoai-base-nats-headless.{{ $.Release.Namespace }}.svc.cluster.local:8222"
        account: '$G'
        stream: {{ $.Values.nats.stream.name }}
        consumer: finetuning-nats-consumer
        lagThreshold: '5'
        activationLagThreshold: '1'
        useHttps: 'false'
{{- end }}