apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ .Values.finetuning.name }}
spec:
  jobTargetRef:
    parallelism: 1
    completions: 1
    template:
      spec:
        {{- with .Values.finetuning.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        containers:
          - name: redis-client
            image: {{ .Values.finetuning.image.registry }}/{{ .Values.finetuning.image.repository }}:{{ .Values.finetuning.image.tag }}
            imagePullPolicy: {{ .Values.finetuning.image.pullPolicy }}
            resources:
              {{- toYaml .Values.finetuning.resources | nindent 14 }}
            env:
              {{- include "dynamoai.commonEnv" . | nindent 12 }}
              {{- include "dynamoai.finetuningScaledJobEnv" . | nindent 12 }}
              {{- with .Values.finetuning.extraEnv }}
              {{- toYaml . | nindent 12 }}
              {{- end }}
              {{- if .Values.nats.enabled -}}
              - name: NATS_SUBJECT_FILTER
                value: {{ .Values.finetuning.nats.subjectFilter}}
              - name: NATS_CONSUMER_NAME
                value: finetuning-nats-consumer
              {{- end -}}
            {{- if $.Values.global.config.proxy }}
            envFrom:
              - configMapRef:
                  name: {{ $.Values.global.config.proxy }}
            {{- end }}
        restartPolicy: {{ .Values.finetuning.restartPolicy }}
  pollingInterval: {{ .Values.finetuning.pollingInterval }}
  minReplicaCount: {{ .Values.finetuning.minReplicaCount }}
  maxReplicaCount: {{ .Values.finetuning.maxReplicaCount }}
  successfulJobsHistoryLimit: {{ .Values.finetuning.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.finetuning.failedJobsHistoryLimit }}
  triggers:
    - type: external
      metadata:
        scalerAddress: {{ .Values.metricsServer.address }}
        listName: {{ .Values.finetuning.name }}
        listLength: '1'
