apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dynamoai.fullname" . }}-{{ .Values.api.name }}-config
  labels:
    {{- include "dynamoai.labels" . | nindent 4 }}
  annotations:
    {{- include "dynamoai.annotations" . | nindent 4 }}
data:
  host: "{{ include "dynamoai.fullname" . }}-{{ .Values.api.name }}.{{ .Release.Namespace }}.svc.cluster.local"
  domain: "http://{{ .Values.api.ingress.host }}/api"
  port: "{{ .Values.api.service.port }}"
  address: "{{ include "dynamoai.fullname" . }}-{{ .Values.api.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.api.service.port }}"
