{{- if and .Values.api.enabled .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dynamoai.fullname" . }}-{{ .Values.api.name }}-ingress
  labels:
    {{- include "dynamoai.labels" . | nindent 4 }}
    {{- with .Values.api.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "dynamoai.annotations" . | nindent 4 }}
    {{- with .Values.api.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.api.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.api.ingress.host }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "dynamoai.fullname" . }}-{{ .Values.api.name }}
                port:
                  number: {{ .Values.api.service.port }}
  tls:
    {{- toYaml .Values.api.ingress.tls | nindent 4 }}
{{- end }}
