apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dynamoai.fullname" . }}-{{ .Values.keycloak.name }}
  labels:
    app: {{ include "dynamoai.fullname" . }}-{{ .Values.keycloak.name }}
    {{- include "dynamoai.labels" . | nindent 4 }}
    {{- with .Values.keycloak.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    annotations:
    {{- include "dynamoai.annotations" . | nindent 4 }}
    {{- with .Values.keycloak.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ include "dynamoai.fullname" . }}-{{ .Values.keycloak.name }}
      {{- include "dynamoai.selectorLabels" . | nindent 6 }}
  {{- if not .Values.keycloak.hpa.enabled }}
  replicas: {{ .Values.keycloak.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "dynamoai.fullname" . }}-{{ .Values.api.name }}
        {{- include "dynamoai.labels" . | nindent 8 }}
        {{- with .Values.api.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "dynamoai.annotations" . | nindent 8 }}
        {{- with .Values.api.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.keycloak.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dynamoai.serviceAccountName" . }}
      {{- with .Values.api.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      containers:
        - name: {{ .Values.keycloak.name }}
          securityContext:
            {{- toYaml .Values.keycloak.securityContext | nindent 12 }}
          image: "{{ .Values.keycloak.image.registry }}/{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.keycloak.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.keycloak.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.keycloak.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.keycloak.resources | nindent 12 }}
          {{- with .Values.keycloak.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.keycloak.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.keycloak.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.keycloak.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.keycloak.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
