apiVersion: v1
kind: Service
metadata:
  name: {{ include "dynamoai.fullname" . }}
  labels:
    {{- include "dynamoai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - port: {{ .Values.keycloak.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dynamoai.selectorLabels" . | nindent 4 }}
