# Default values for dynamoai.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  nameOverride: "dynamoai"
  fullnameOverride: "dynamoai"
  serviceAccount:
    name: "dynamoai-service-account"
  secrets:
    mongodb: dynamoai-mongodb-secret
    postgres: dynamoai-postgres-secret
    redis: dynamoai-redis-secret
    common: dynamoai-common-secret
  config:
    common: dynamoai-common-config
    proxy: dynamoai-proxy-config
  awsRegion: "us-east-1"

keycloak:
  enabled: true
  fullnameOverride: keycloak
  auth:
    adminUser: "admin"
    adminPassword: "" # TODO

  adminIngress:
    enabled: true
    ingressClassName: nginx
    path: /keycloak/?(.*)
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    hostname: dev.dynamofl.com

  keycloakconfigcli:
    enabled: true
    configuration:
      'dynamoai-realm.json': ""

  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--hostname-url=https://dev.dynamofl.com/keycloak --hostname-admin-url=https://dev.dynamofl.com/keycloak"

  postgresql:
    enabled: false
    externalDatabase: # TODO
      host: ""
      user: ""
      password: ""
      database: keycloak

  service:
    type:
    annotations:
      service.beta.kubernetes.ent.yaml/aws-load-balancer-additional-resource-tags: 'Name=dfl-keycloak-ingress'
      service.beta.kubernetes.ent.yaml/aws-load-balancer-backend-protocol: 'http'
      service.beta.kubernetes.ent.yaml/aws-load-balancer-internal: false
