{{- if $.Values.nats.enabled }}
{{- range .Values.pentest.gpuConfig }}
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: {{ include "dynamoai.natsGpuConsumerName" (dict "subjectprefix" $.Values.natsQueueGpuSubjectPrefix "type" .type "count" .count)  }}
spec:
    streamName: {{ $.Values.nats.stream.name }}
    durableName: {{ $.Values.nats.stream.name }}
    filterSubject: {{ include "dynamoai.natsGpuConsumerSubjectFilter" (dict "subjectprefix" $.Values.natsQueueGpuSubjectPrefix "type" .type "count" .count) }}
    ackPolicy: 'explicit'
    ackWait: '60s'
    maxAckPending: 100
    maxDeliver: 3
{{- end }}

---

{{- range .Values.pentest.memoryConfig }}
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: {{ include "dynamoai.natsVramConsumerName" (dict "subjectprefix" $.Values.natsQueueVramSubjectPrefix "type" .type )  }}
spec:
    streamName: {{ $.Values.nats.stream.name }}
    durableName: {{ $.Values.nats.stream.name }}
    filterSubject: {{ include "dynamoai.natsVramConsumerSubjectFilter" (dict "subjectprefix" $.Values.natsQueueVramSubjectPrefix "type" .type ) }}
    ackPolicy: 'explicit'
    ackWait: '60s'
    maxAckPending: 100
    maxDeliver: 3
{{- end }}
{{- end }}