{{- if .Values.pentest.enabled }}
{{- range .Values.pentest.memoryConfig }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: pentest-{{ .type }}-scaledjob
spec:
  jobTargetRef:
    parallelism: 1
    completions: 1
    template:
      spec:
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
          - key: gpu-memory
            operator: Equal
            value: {{ .type | quote }}
            effect: NoSchedule
        volumes:
          - name: api-key-secret-volume
            secret:
              secretName: {{ $.Values.global.secrets.apikeys }}
        containers:
          - name: redis-client
            image: {{ $.Values.pentest.image.registry }}/{{ $.Values.pentest.image.repository }}:{{ $.Values.pentest.image.tag }}
            imagePullPolicy: {{ $.Values.pentest.image.pullPolicy }}
            volumeMounts:
              - name: api-key-secret-volume
                mountPath: /var/secrets
                readOnly: true
            resources:
              requests:
                nvidia.com/gpu: {{ .count | quote }}
              limits:
                nvidia.com/gpu: {{ .count | quote }}
            env:
              {{- include "dynamoai.commonEnv" $ | nindent 12 }}
              {{- include "dynamoai.pentestEnv" $ | nindent 12 }}
              {{- include "dynamoai.scaledJobCommonEnv" $ | nindent 12 }}
              {{- include "dynamoai.gpuMemoryCountScaledJobEnv" . | nindent 12 }}
              {{- with $.Values.pentest.extraEnv }}
              {{- toYaml . | nindent 12 }}
              {{- end }}
            {{- if $.Values.global.config.proxy }}
            envFrom:
              - configMapRef:
                  name: {{ $.Values.global.config.proxy }}
            {{- end }}
        restartPolicy: Never
  pollingInterval: 10
  minReplicaCount: 0
  maxReplicaCount: 100
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  triggers:
    - type: external
      metadata:
        scalerAddress: {{ $.Values.metricsServer.address }}
        listName: pentest-{{ .type }}
        listLength: '1'
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "nats-headless.{{ $.Release.Namespace }}.svc.cluster.local:8222"
        account: '$G'
        stream: {{ $.Values.nats.stream.name }}
        consumer: {{ include "dynamoai.natsVramConsumerName" (dict "subjectprefix" $.Values.natsQueueVramSubjectPrefix "type" .type)  }}
        lagThreshold: '5'
        activationLagThreshold: '1'
        useHttps: 'false'
{{- end }}
{{- end }}