awsEbsCsiDriver:
  enabled: true

karpenter:
  enabled: true
  imagePullPolicy: IfNotPresent
  serviceAccount:
    create: true
    name: karpenter
    annotations:
      eks.amazonaws.com/role-arn: ""
  replicas: 2
  podLabels:
    app: karpenter
  settings:
    clusterName: "YOUR CLUSTER NAME"
  nodeSelector:
    kubernetes.io/os: linux
    # specify another other nodeSelector labels for default node group
  controller:
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi
  

nginx:
  enabled: true
  controller:
    enabled: true
    service:
      type: "LoadBalancer"
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "false"
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:260010166034:certificate/0698ef0b-27e6-46d1-9b1d-a555b6cf7112"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3000"
      ports:
        http: 80
        https: 443
      targetPorts:
        http: http
        https: http
    admissionWebhooks:
      patch:
        enabled: true
      install:
        enabled: true

keda:
  enabled: true

keda-add-ons-http:
  enabled: true
  interceptor:
    responseHeaderTimeout: 30s