# Default values for dynamoai-kube-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Default values for aws-ebs-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
k8Infra:
  subnetAzs:
    - us-west-2a
    - us-west-2b
    - us-west-2c
  privateSubnetIds:
    - subnet-12345678
    - subnet-23456789
    - subnet-34567890
  secondaryPrivateSubnetIds:
    - subnet-87654321
    - subnet-76543210
    - subnet-65432109
  clusterSecurityGroupId: sg-0123456789abcdef0


service:
  port: 80
  
awsEbsCsiDriver:
  enabled: true

karpenter:
  enabled: true
  imagePullPolicy: IfNotPresent
  serviceAccount:
    create: false
  replicas: 1
  podLabels: {
    app: karpenter
  }
  settings: 
    clusterName: dynamofl-aws-default-sandbox
  controller:
    resources: {
      requests: {
        cpu: 1,
        memory: 1Gi
      },
      limits: {
        cpu: 1,
        memory: 1Gi
      }
    }

nginx:
  enabled: true
  controller:
    enabled: true
    service:
      type: "LoadBalancer"
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "false"
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:260010166034:certificate/0698ef0b-27e6-46d1-9b1d-a555b6cf7112" 
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3000"
      ports:
        http: 80
        https: 443
      targetPorts:
        http: http
        https: http
    admissionWebhooks:
      patch:
        enabled: true
      install:
        enabled: true

keda:
  enabled: true

keda-add-ons-http:
  enabled: true
  interceptor:
    responseHeaderTimeout: 30s